//////////////////////////////////////
//
// Graphics .H file for .HP1
// IGRAB-ed on Sat Nov 04 13:26:46 2023
//
//////////////////////////////////////

typedef enum {



		ENUMEND
	     } graphicnums;

//
// Data LUMPs
//

//
// Amount of each data item
//
#define NUMCHUNKS    738
#define NUMFONT      0
#define NUMFONTM     0
#define NUMPICS      0
#define NUMPICM      0
#define NUMSPRITES   0
#define NUMTILE8     0
#define NUMTILE8M    0
#define NUMTILE16    270
#define NUMTILE16M   468
#define NUMTILE32    0
#define NUMTILE32M   0
#define NUMEXTERNS   0
//
// File offsets for data items
//
#define STARTFONT    0
#define STARTFONTM   0
#define STARTPICS    0
#define STARTPICM    0
#define STARTSPRITES 0
#define STARTTILE8   0
#define STARTTILE8M  0
#define STARTTILE16  0
#define STARTTILE16M 270
#define STARTTILE32  738
#define STARTTILE32M 738
#define STARTEXTERNS 738

//
// Thank you for using IGRAB!
//
